runtime: go
api_version: go1

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 128

handlers:
- url: /favicon.ico
  static_files: asset/image/favicon.ico
  upload: asset/image/favicon.ico
- url: /css
  static_dir: asset/css
- url: /js
  static_dir: asset/js
- url: /fonts
  static_dir: asset/fonts
- url: /.*
  script: _go_app
  login: admin
  secure: always
